### ISSUE TITLE
PCIE转接板的问题

### ISSUE THREAD

**Issue by NoopLoop00** [KCORES/KCORES-5070#5]
关于供电方案有个问题，我看原理图标注1-2是自适应电压，是不是把3脚悬空就可以了？还需要配合电路改造吗

**Comment by alphaarea** [comment]
供电方案没什么可改的, 用 PCIe 就配 12V 电源.

转接卡上加一个能跑 5A 的 19V - 12V 降压电路随便就是一二十块钱出去了
